### ISSUE TITLE
missing nat adapter configuration step for ssh

### ISSUE THREAD

**Issue by Zackmortar** [gemartin99/Born2beroot-Tutorial#11]
you have to add network adapter 1 with portforwarding rules hostip xxxx 4242 10.0.2.15 4242
the xxxx ip is to be replaced with the ip found when you click tools then create host only networks vboxnet
(its in the ipv4 prefix)

**Comment by gemartin99** [comment]
Everything you are talking about can be found in section 4.6. I don't know if you are referring to something else, if so, let me know.

**Comment by Zackmortar** [comment]
The ssh setup should work normally,but testing it out with a terminal
becomes an issue in my(and the students trying it out with me) experience

**Comment by gemartin99** [comment]
Write me via slack with screenshots of exactly what is happening to you and we'll see how to fix it :)
