### ISSUE TITLE
El fichero que recoge el historial de comandos sudo se pide en /var/log/sudo/sudo.log

### ISSUE THREAD

**Issue by sadelax** [gemartin99/Born2beroot-Tutorial#5]

**Comment by gemartin99** [comment]
Buenas Sadelax, agradezco tu comentario. Según el subject en ingles ( que es el que hay que seguir ) lo único que especifica es que el historial de comandos se almacene en esta ruta -> /var/log/sudo/ el nombre del fichero donde se almacena el historial es opcional. En mi caso le puse sudo_config , ahí es donde se almacena todo el historial y en teoría esta todo en orden, corrígeme si me equivoco. Espero que tu duda haya sido aclarada. Gracias de nuevo.
