### ISSUE TITLE
Falta un signo de puntuación

### ISSUE THREAD

**Issue by NorielSylvire** [gemartin99/Born2beroot-Tutorial#6]
Así es, ¡soy de esos!

En el README.md, en el apartado 5-6, pone 
> haremos uso del comando `vmstat` este muestra estadísticas del sistema

Para que la oración se lea de manera correcta, hace falta algún signo de puntuación, ya sea una coma:

> haremos uso del comando `vmstat`, este muestra estadísticas del sistema

o preferiblemente un punto:

> haremos uso del comando `vmstat`. Este muestra estadísticas del sistema

**Comment by gemartin99** [comment]
Solucionado! Despues de un buen rato he conseguido arreglarlo. Gracias 😁

**Comment by NorielSylvire** [comment]
Espero que no haya costado demasiado.
Ahora en serio, qué rápido lo has arreglado😯
